SLACK_TOKEN=
SLACK_NEW_CHANNEL_NOTIFICATION_CHANNEL_ID=

run:
	env SLACK_TOKEN=$(SLACK_TOKEN) \
		SLACK_NEW_CHANNEL_NOTIFICATION_CHANNEL_ID=$(SLACK_NEW_CHANNEL_NOTIFICATION_CHANNEL_ID) \
		go run ./main.go 

help:
	@cat Makefile

build:
	GOOS=$(GOOS) GOARCH=$(GOARCH) go build
